/* 合并报工接单保存：抬头 X_ONLINE_SIGN + 明细 X_ONLINE_SIGN1（DocEntry IDENTITY） */

IF OBJECT_ID(N'dbo.X_ONLINE_SIGN', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.X_ONLINE_SIGN (
    DocEntry INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_X_ONLINE_SIGN PRIMARY KEY,
    Remarks NVARCHAR(500) NULL,
    StepCode NVARCHAR(100) NULL,
    StepName NVARCHAR(200) NULL,
    SignAt DATETIME2(0) NULL,
    OperatorCodes NVARCHAR(500) NULL
  );
END;

IF OBJECT_ID(N'dbo.X_ONLINE_SIGN1', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.X_ONLINE_SIGN1 (
    DocEntry INT NOT NULL,
    LineId INT NOT NULL,
    BaseEntry INT NOT NULL,
    Quantity DECIMAL(19, 2) NULL,
    LastStepCode NVARCHAR(100) NULL,
    LastStepName NVARCHAR(200) NULL,
    LastStepTime DATETIME2(0) NULL,
    PC NVARCHAR(200) NULL,
    ItemName NVARCHAR(500) NULL,
    BaseOType NVARCHAR(20) NULL,
    BaseOEntry INT NULL,
    BaseOLine INT NULL,
    CONSTRAINT PK_X_ONLINE_SIGN1 PRIMARY KEY (DocEntry, LineId),
    CONSTRAINT FK_XOS1_X_ONLINE_SIGN FOREIGN KEY (DocEntry) REFERENCES dbo.X_ONLINE_SIGN (DocEntry) ON DELETE CASCADE
  );
  CREATE INDEX idx_xos1_base ON dbo.X_ONLINE_SIGN1 (BaseEntry);
END;

/* 已有库升级：抬头扩展字段 */
IF OBJECT_ID(N'dbo.X_ONLINE_SIGN', N'U') IS NOT NULL AND COL_LENGTH(N'dbo.X_ONLINE_SIGN', N'StepCode') IS NULL
  ALTER TABLE dbo.X_ONLINE_SIGN ADD StepCode NVARCHAR(100) NULL;

IF OBJECT_ID(N'dbo.X_ONLINE_SIGN', N'U') IS NOT NULL AND COL_LENGTH(N'dbo.X_ONLINE_SIGN', N'StepName') IS NULL
  ALTER TABLE dbo.X_ONLINE_SIGN ADD StepName NVARCHAR(200) NULL;

IF OBJECT_ID(N'dbo.X_ONLINE_SIGN', N'U') IS NOT NULL AND COL_LENGTH(N'dbo.X_ONLINE_SIGN', N'SignAt') IS NULL
  ALTER TABLE dbo.X_ONLINE_SIGN ADD SignAt DATETIME2(0) NULL;

IF OBJECT_ID(N'dbo.X_ONLINE_SIGN', N'U') IS NOT NULL AND COL_LENGTH(N'dbo.X_ONLINE_SIGN', N'OperatorCodes') IS NULL
  ALTER TABLE dbo.X_ONLINE_SIGN ADD OperatorCodes NVARCHAR(500) NULL;

IF OBJECT_ID(N'dbo.X_ONLINE_SIGN', N'U') IS NOT NULL AND COL_LENGTH(N'dbo.X_ONLINE_SIGN', N'SignType') IS NULL
  ALTER TABLE dbo.X_ONLINE_SIGN ADD SignType NVARCHAR(20) NULL;

/* 明细：上道工序字段 */
IF OBJECT_ID(N'dbo.X_ONLINE_SIGN1', N'U') IS NOT NULL AND COL_LENGTH(N'dbo.X_ONLINE_SIGN1', N'LastStepCode') IS NULL
  ALTER TABLE dbo.X_ONLINE_SIGN1 ADD LastStepCode NVARCHAR(100) NULL;

IF OBJECT_ID(N'dbo.X_ONLINE_SIGN1', N'U') IS NOT NULL AND COL_LENGTH(N'dbo.X_ONLINE_SIGN1', N'LastStepName') IS NULL
  ALTER TABLE dbo.X_ONLINE_SIGN1 ADD LastStepName NVARCHAR(200) NULL;

IF OBJECT_ID(N'dbo.X_ONLINE_SIGN1', N'U') IS NOT NULL AND COL_LENGTH(N'dbo.X_ONLINE_SIGN1', N'LastStepTime') IS NULL
  ALTER TABLE dbo.X_ONLINE_SIGN1 ADD LastStepTime DATETIME2(0) NULL;

IF OBJECT_ID(N'dbo.X_ONLINE_SIGN1', N'U') IS NOT NULL AND COL_LENGTH(N'dbo.X_ONLINE_SIGN1', N'PC') IS NULL
  ALTER TABLE dbo.X_ONLINE_SIGN1 ADD PC NVARCHAR(200) NULL;

IF OBJECT_ID(N'dbo.X_ONLINE_SIGN1', N'U') IS NOT NULL AND COL_LENGTH(N'dbo.X_ONLINE_SIGN1', N'ItemName') IS NULL
  ALTER TABLE dbo.X_ONLINE_SIGN1 ADD ItemName NVARCHAR(500) NULL;

IF OBJECT_ID(N'dbo.X_ONLINE_SIGN1', N'U') IS NOT NULL AND COL_LENGTH(N'dbo.X_ONLINE_SIGN1', N'BaseOType') IS NULL
  ALTER TABLE dbo.X_ONLINE_SIGN1 ADD BaseOType NVARCHAR(20) NULL;

IF OBJECT_ID(N'dbo.X_ONLINE_SIGN1', N'U') IS NOT NULL AND COL_LENGTH(N'dbo.X_ONLINE_SIGN1', N'BaseOEntry') IS NULL
  ALTER TABLE dbo.X_ONLINE_SIGN1 ADD BaseOEntry INT NULL;

IF OBJECT_ID(N'dbo.X_ONLINE_SIGN1', N'U') IS NOT NULL AND COL_LENGTH(N'dbo.X_ONLINE_SIGN1', N'BaseOLine') IS NULL
  ALTER TABLE dbo.X_ONLINE_SIGN1 ADD BaseOLine INT NULL;

/* 移除旧版明细工序列（若存在） */
IF OBJECT_ID(N'dbo.X_ONLINE_SIGN1', N'U') IS NOT NULL AND COL_LENGTH(N'dbo.X_ONLINE_SIGN1', N'SetupCode') IS NOT NULL
  ALTER TABLE dbo.X_ONLINE_SIGN1 DROP COLUMN SetupCode;
